// Play track — side projects, posters, motion studies, GIFs, and live experiments.
// Two sources merge into PLAY_ITEMS:
//   1. Manual overrides (this file) — for live demos with custom config (Spline scenes,
//      external links, hand-curated chips, descriptions, year overrides). These win when
//      a slug clashes with the manifest.
//   2. Auto-imported manifest (lib/_play-manifest.json) — generated by `npm run sync-play`
//      from images in ~/Design hub/0-Category /<Category>/. The user maintains the
//      iCloud folders as the source of truth; the website re-syncs on demand.

import manifest from "./_play-manifest.json";

export type PlayCategory =
  | "3d-art"
  | "advertising"
  | "animation-and-video"
  | "architecture"
  | "fine-art-and-crafts"
  | "fashion"
  | "game-design"
  | "graphic-design"
  | "interaction-design"
  | "logo-design"
  | "motion-and-film"
  | "product-design"
  | "photography"
  | "sound"
  | "ui-ux"
  | "web-design"
  | "illustration";

export const CATEGORY_LABEL: Record<PlayCategory, string> = {
  "3d-art": "3D Art",
  advertising: "Advertising",
  "animation-and-video": "Animation & Video",
  architecture: "Architecture",
  "fine-art-and-crafts": "Fine Art & Crafts",
  fashion: "Fashion",
  "game-design": "Game Design",
  "graphic-design": "Graphic Design & Branding",
  "interaction-design": "Interaction Design",
  "logo-design": "Logo Design",
  "motion-and-film": "Motion & Film",
  "product-design": "Product Design",
  photography: "Photography",
  sound: "Sound",
  "ui-ux": "UI · UX",
  "web-design": "Web Design",
  illustration: "Illustration",
};

export const CATEGORY_ORDER: PlayCategory[] = [
  "3d-art",
  "graphic-design",
  "illustration",
  "photography",
  "fine-art-and-crafts",
  "interaction-design",
  "logo-design",
  "motion-and-film",
  "animation-and-video",
  "ui-ux",
  "web-design",
  "product-design",
  "game-design",
  "architecture",
  "fashion",
  "advertising",
  "sound",
];

export type PlayKind =
  | "image"
  | "gif"
  | "video"
  | "spline"
  | "external"
  | "embed";

export type PlayItem = {
  slug: string;
  name?: string;
  year: number;
  kind: PlayKind;
  category: PlayCategory;
  aspectRatio?: string;
  chips?: string[];
  description?: string;
  src?: string;
  videoSrc?: string;
  previewVideoSrc?: string;
  embedUrl?: string;
  previewEmbedUrl?: string;
  previewAspectRatio?: string;
  externalUrl?: string;
  splineScene?: string;
  thumbnail?: string;
  hasDetail?: boolean;
};

// ===== Manual overrides — live demos with config that the auto-sync can't infer =====
const MANUAL: PlayItem[] = [
  {
    slug: "3d-fuzzy-magenta",
    name: "Fuzzy Material Reel",
    year: 2026,
    kind: "video",
    category: "3d-art",
    aspectRatio: "4/5",
    chips: ["3D", "Material", "Remotion"],
    description: "A fast-cut Remotion reel from fur material renders.",
    videoSrc: "/play/highlights/fuzzy-hair-reel.mp4",
    previewVideoSrc: "/play/previews/fuzzy-hair-reel-16x9.mp4",
    previewAspectRatio: "16/9",
    thumbnail: "/play/highlights/fuzzy-hair-reel.jpg",
  },
  {
    slug: "3d-iridescent-wave",
    name: "Iridescent Wave",
    year: 2026,
    kind: "video",
    category: "3d-art",
    aspectRatio: "4/5",
    chips: ["3D", "Motion", "Light"],
    description: "A luminous abstract wave study prepared as a looping artifact card.",
    videoSrc: "/play/highlights/iridescent-wave.mp4",
    previewVideoSrc: "/play/previews/iridescent-wave-original.mp4",
    previewAspectRatio: "16/9",
    thumbnail: "/play/highlights/iridescent-wave.jpg",
  },
  {
    slug: "graphic-bauhaus-letters",
    name: "Bauhaus Letters",
    year: 2026,
    kind: "video",
    category: "graphic-design",
    aspectRatio: "4/5",
    chips: ["Graphic", "Motion", "Type"],
    description: "A geometric black-and-white motion study for the playground wall.",
    videoSrc: "/play/highlights/name-motion.mp4",
    previewVideoSrc: "/play/previews/name-motion-original.mp4",
    previewAspectRatio: "16/9",
    thumbnail: "/play/highlights/name-motion.jpg",
  },
  {
    slug: "beginning-of-winter",
    name: "Beginning of Winter",
    year: 2026,
    kind: "video",
    category: "animation-and-video",
    aspectRatio: "4/5",
    chips: ["Seasonal", "Motion", "Visual"],
    description: "A cropped visual loop from the Beginning of Winter motion study.",
    videoSrc: "/play/highlights/beginning-of-winter.mp4",
    previewVideoSrc: "/play/previews/beginning-of-winter-original.mp4",
    previewAspectRatio: "4/3",
    thumbnail: "/play/highlights/beginning-of-winter.jpg",
  },
  {
    slug: "demain-day-night",
    name: "DeMain Day / Night",
    year: 2022,
    kind: "video",
    category: "3d-art",
    aspectRatio: "4/5",
    chips: ["3D", "Environment", "Day Night"],
    description: "A day-to-night loop from the DeMain city environment.",
    videoSrc: "/play/highlights/demain-day-night.mp4",
    previewVideoSrc: "/play/previews/demain-day-night-original.mp4",
    previewAspectRatio: "1080/2340",
    thumbnail: "/play/highlights/demain-day-night.jpg",
  },
  {
    slug: "ai-see-motion-study",
    name: "AISEE",
    year: 2023,
    kind: "video",
    category: "motion-and-film",
    aspectRatio: "4/5",
    chips: ["AI Film", "Runway", "48h Sprint"],
    description:
      "A 48-hour AI film sprint exploring surreal self-perception through prompt-led image generation, Runway motion, sound, and edit direction.",
    videoSrc: "/play/highlights/isee.mp4",
    previewEmbedUrl: "https://www.youtube.com/embed/yp9JvKkmid8?rel=0&modestbranding=1",
    previewAspectRatio: "16/9",
    thumbnail: "/play/highlights/isee.jpg",
  },
  {
    slug: "lantern-festival-genai",
    name: "Lantern Festival GenAI Promo",
    year: 2024,
    kind: "video",
    category: "advertising",
    aspectRatio: "4/5",
    chips: ["Commercial", "Runway", "GenAI Video"],
    description:
      "An early-state GenAI commercial video workflow for a large-scale Guizhou lantern-festival campaign.",
    videoSrc: "/play/highlights/lantern-festival-genai-card.mp4",
    previewVideoSrc: "/play/previews/lantern-festival-genai-original.mp4",
    previewAspectRatio: "16/9",
    thumbnail: "/play/highlights/lantern-festival-genai.jpg",
  },
  {
    slug: "luna-archive-interface",
    name: "Lunacy Moon Archive",
    year: 2022,
    kind: "video",
    category: "interaction-design",
    aspectRatio: "4/5",
    chips: ["Interface", "Archive", "Speculative UI"],
    description: "A speculative archive interface edited into a product-card loop.",
    videoSrc: "/play/highlights/archive-interface.mp4",
    previewEmbedUrl: "https://player.vimeo.com/video/883707048?title=0&byline=0&portrait=0&badge=0&autopause=0",
    previewAspectRatio: "16/9",
    thumbnail: "/play/highlights/archive-interface.jpg",
  },
  {
    slug: "scfa-motion-study",
    name: "SCFA Design Systems",
    year: 2022,
    kind: "video",
    category: "animation-and-video",
    aspectRatio: "4/5",
    chips: ["Motion", "3D", "Identity"],
    description: "A cropped 3D identity motion study prepared for looping cards.",
    videoSrc: "/play/highlights/motion-study-10.mp4",
    previewVideoSrc: "/play/previews/motion-study-10-original.mp4",
    previewAspectRatio: "16/9",
    thumbnail: "/play/highlights/motion-study-10.jpg",
  },
  {
    slug: "sprayscape-mr",
    name: "SprayScape MR",
    year: 2026,
    kind: "video",
    category: "interaction-design",
    aspectRatio: "4/5",
    chips: ["MR", "Spatial Archive", "Street Art"],
    description: "A mixed-reality follow-up for archiving, replaying, and remixing street art in its urban context.",
    videoSrc: "/play/highlights/sprayscape-mr-card.mp4",
    previewVideoSrc: "/play/previews/sprayscape-mr-original.mp4",
    previewAspectRatio: "16/9",
    thumbnail: "/play/highlights/sprayscape-mr.jpg",
  },
  {
    slug: "spline-playground",
    name: "Spline Playground",
    year: 2025,
    kind: "spline",
    category: "3d-art",
    aspectRatio: "16/10",
    chips: ["3D", "Spline", "Next.js"],
    description: "Interactive Spline scene — drag to orbit, scroll to zoom.",
    hasDetail: true,
    splineScene: "/play/spline-playground/scene.splinecode",
  },
  // Add more manual entries here when you want hand-tuned chips / descriptions.
  // Slug clashes with the manifest get resolved in favour of the manual entry.
];

// ===== Merge manifest + manual =====
type ManifestItem = {
  slug: string;
  category: PlayCategory;
  kind: PlayKind;
  src?: string;
  videoSrc?: string;
  embedUrl?: string;
  aspectRatio?: string;
  name?: string;
  year?: number;
};

const manifestItems = (manifest as { items: ManifestItem[] }).items.map(
  (m): PlayItem => ({
    slug: m.slug,
    category: m.category,
    kind: m.kind,
    src: m.src,
    videoSrc: m.videoSrc,
    embedUrl: m.embedUrl,
    aspectRatio: m.aspectRatio,
    name: m.name,
    year: m.year ?? new Date().getFullYear(),
  })
);

const manualSlugs = new Set(MANUAL.map((m) => m.slug));
const merged = [
  ...MANUAL,
  ...manifestItems.filter((m) => !manualSlugs.has(m.slug)),
];

export const PLAY_ITEMS: PlayItem[] = merged;

export function findPlayItem(slug: string) {
  return PLAY_ITEMS.find((p) => p.slug === slug);
}

export function itemsByCategory() {
  const map = new Map<PlayCategory, PlayItem[]>();
  for (const cat of CATEGORY_ORDER) map.set(cat, []);
  for (const item of PLAY_ITEMS) {
    if (!map.has(item.category)) map.set(item.category, []);
    map.get(item.category)!.push(item);
  }
  const filtered: { category: PlayCategory; items: PlayItem[] }[] = [];
  for (const cat of CATEGORY_ORDER) {
    const items = map.get(cat) ?? [];
    if (items.length > 0) filtered.push({ category: cat, items });
  }
  return filtered;
}
