// Play track — side projects, posters, motion studies, GIFs, and live experiments.
// Two sources merge into PLAY_ITEMS:
//   1. Manual overrides (this file) — for live demos with custom config (Spline scenes,
//      external links, hand-curated chips, descriptions, year overrides). These win when
//      a slug clashes with the manifest.
//   2. Auto-imported manifest (lib/_play-manifest.json) — generated by `npm run sync-play`
//      from images in ~/Design hub/0-Category /<Category>/. The user maintains the
//      iCloud folders as the source of truth; the website re-syncs on demand.

import manifest from "./_play-manifest.json";

export type PlayCategory =
  | "3d-art"
  | "advertising"
  | "animation-and-video"
  | "architecture"
  | "fine-art-and-crafts"
  | "fashion"
  | "game-design"
  | "graphic-design"
  | "interaction-design"
  | "logo-design"
  | "motion-and-film"
  | "product-design"
  | "photography"
  | "sound"
  | "ui-ux"
  | "web-design"
  | "illustration";

export const CATEGORY_LABEL: Record<PlayCategory, string> = {
  "3d-art": "3D Art",
  advertising: "Advertising",
  "animation-and-video": "Animation & Video",
  architecture: "Architecture",
  "fine-art-and-crafts": "Fine Art & Crafts",
  fashion: "Fashion",
  "game-design": "Game Design",
  "graphic-design": "Graphic Design & Branding",
  "interaction-design": "Interaction Design",
  "logo-design": "Logo Design",
  "motion-and-film": "Motion & Film",
  "product-design": "Product Design",
  photography: "Photography",
  sound: "Sound",
  "ui-ux": "UI · UX",
  "web-design": "Web Design",
  illustration: "Illustration",
};

export const CATEGORY_ORDER: PlayCategory[] = [
  "3d-art",
  "graphic-design",
  "illustration",
  "photography",
  "fine-art-and-crafts",
  "interaction-design",
  "logo-design",
  "motion-and-film",
  "animation-and-video",
  "ui-ux",
  "web-design",
  "product-design",
  "game-design",
  "architecture",
  "fashion",
  "advertising",
  "sound",
];

export type PlayKind =
  | "image"
  | "gif"
  | "video"
  | "spline"
  | "external"
  | "embed";

export type PlayItem = {
  slug: string;
  name?: string;
  year: number;
  kind: PlayKind;
  category: PlayCategory;
  aspectRatio?: string;
  chips?: string[];
  description?: string;
  src?: string;
  videoSrc?: string;
  embedUrl?: string;
  externalUrl?: string;
  splineScene?: string;
  thumbnail?: string;
  hasDetail?: boolean;
};

// ===== Manual overrides — live demos with config that the auto-sync can't infer =====
const MANUAL: PlayItem[] = [
  {
    slug: "spline-playground",
    name: "Spline Playground",
    year: 2025,
    kind: "spline",
    category: "3d-art",
    aspectRatio: "16/10",
    chips: ["3D", "Spline", "Next.js"],
    description: "Interactive Spline scene — drag to orbit, scroll to zoom.",
    hasDetail: true,
    splineScene: "/play/spline-playground/scene.splinecode",
  },
  // Add more manual entries here when you want hand-tuned chips / descriptions.
  // Slug clashes with the manifest get resolved in favour of the manual entry.
];

// ===== Merge manifest + manual =====
type ManifestItem = {
  slug: string;
  category: PlayCategory;
  kind: PlayKind;
  src?: string;
  videoSrc?: string;
  embedUrl?: string;
  aspectRatio?: string;
  name?: string;
  year?: number;
};

const manifestItems = (manifest as { items: ManifestItem[] }).items.map(
  (m): PlayItem => ({
    slug: m.slug,
    category: m.category,
    kind: m.kind,
    src: m.src,
    videoSrc: m.videoSrc,
    embedUrl: m.embedUrl,
    aspectRatio: m.aspectRatio,
    name: m.name,
    year: m.year ?? new Date().getFullYear(),
  })
);

const manualSlugs = new Set(MANUAL.map((m) => m.slug));
const merged = [
  ...MANUAL,
  ...manifestItems.filter((m) => !manualSlugs.has(m.slug)),
];

export const PLAY_ITEMS: PlayItem[] = merged;

export function findPlayItem(slug: string) {
  return PLAY_ITEMS.find((p) => p.slug === slug);
}

export function itemsByCategory() {
  const map = new Map<PlayCategory, PlayItem[]>();
  for (const cat of CATEGORY_ORDER) map.set(cat, []);
  for (const item of PLAY_ITEMS) {
    if (!map.has(item.category)) map.set(item.category, []);
    map.get(item.category)!.push(item);
  }
  const filtered: { category: PlayCategory; items: PlayItem[] }[] = [];
  for (const cat of CATEGORY_ORDER) {
    const items = map.get(cat) ?? [];
    if (items.length > 0) filtered.push({ category: cat, items });
  }
  return filtered;
}
